### ISSUE TITLE
메모리 오버 이슈

### ISSUE THREAD

**Issue by Sihan-Son** [Sihan-Son/animal_classification#3]
배치 없이 이미지 학습을 진행하니까
데이터 셋 기준으로 약 500개 이미지가 넘어가면 out of memory와 메모리 중첩 이슈로 프로그램이 죽음

**Comment by janghaeun** [comment]
확인

**Comment by Sihan-Son** [comment]
batch_size 10에서 600장까지 oom 없이 학습 가능

**Comment by Sihan-Son** [comment]
이거 때문에 정확도 50-52%
