### ISSUE TITLE
[질문] Django에서의 이미지 처리 프로세스 관련

### ISSUE THREAD

**Issue by JhoLee** [Sihan-Son/animal_classification#7]
1) 본 프로젝트 최종 기능이 "사용자가 본인의 이미지를 본 시스템이 구분하도록하는 것"으로 알고 있는데 이것이 맞는지
2-1) 맞다면, 이 때 이미지를 서버에 업로드 혹은 어떤 방식으로 받게 되는지?
2-2) 아니라면, ...

**Comment by Sihan-Son** [comment]
굳이 저장 안하고 임시저장 형태로 돌려도 될거 같은데

**Comment by JhoLee** [comment]
오케이.  코드 완성되고 서버 구축 시작하면 그 때 다시 봐야겠네.
